INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(184,'Celebrities & Entertainment News',3,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(316,'Comics & Animation',3,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(612,'Entertainment Industry',3,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(569,'Events & Listings',3,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(539,'Fun & Trivia',3,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(182,'Humor',3,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(34,'Movies',3,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(35,'Music & Audio',3,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(33,'Offbeat',3,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(613,'Online Media',3,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(23,'Performing Arts',3,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(36,'TV & Video',3,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(24,'Visual Art & Design',3,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1191,'Bicycles & Accessories',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1140,'Boats & Watercraft',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1213,'Campers & RVs',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1013,'Classic Vehicles',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1214,'Commercial Vehicles',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(806,'Custom & Performance Vehicles',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(810,'Hybrid & Alternative Vehicles',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1317,'Microcars & City Cars',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(273,'Motorcycles',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(148,'Off-Road Vehicles',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1147,'Personal Aircraft',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1212,'Scooters & Mopeds',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(610,'Trucks & SUVs',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(815,'Vehicle Brands',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1294,'Vehicle Codes & Driving Laws',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(138,'Vehicle Maintenance',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(89,'Vehicle Parts & Accessories',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(473,'Vehicle Shopping',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(803,'Vehicle Shows',47,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1219,'Beauty Pageants',44,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(239,'Body Art',44,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1220,',Cosmetic Procedures',44,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(147,'Cosmetology & Beauty Professionals',44,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(143,'Face & Body Care',44,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(185,'Fashion & Style',44,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(94,'Fitness',44,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(146,'Hair Care',44,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(145,'Spas & Beauty Services',44,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(236,'Weight Loss',44,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(355,'Book Retailers',22,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1183,'Children''s Literature',22,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(608,'E-Books',22,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(540,'Fan Fiction',22,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1184,'Literary Classics',22,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(412,'Magazines',22,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(565,'Poetry',22,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1177,'Writers Resources',22,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(25,'Advertising & Marketing',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(356,'Aerospace & Defense',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(46,'Agriculture & Forestry',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1190,'Automotive Industry',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(799,'Business Education',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1138,'Business Finance',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1159,'Business Operations',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(329,'Business Services',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(288,'Chemicals Industry',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(48,'Construction & Maintenance',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(233,'Energy & Utilities',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(955,'Hospitality Industry',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(287,'Industrial Materials & Equipment',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(49,'Manufacturing',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(606,'Metals & Mining',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(255,'Pharmaceuticals & Biotech',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1176,'Printing & Publishing',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1199,'Professional & Trade Associations',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(841,'Retail Trade',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(551,'Small Business',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(566,'Textiles & Nonwovens',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(50,'Transportation & Logistics',12,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1300,'CAD & CAM',5,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(30,'Computer Hardware',5,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(314,'Computer Security',5,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(78,'Consumer Electronics',5,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(434,'Electronics & Electrical',5,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(77,'Enterprise Technology',5,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(311,'Networking',5,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(31,'Programming',5,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(32,'Software',5,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(278,'Accounting & Auditing',7,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(37,'Banking',7,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(279,'Credit & Lending',7,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(903,'Financial Planning & Management',7,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1282,'"Grants, Scholarships & Financial Aid"',7,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(38,'Insurance',7,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(107,'Investing',7,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(560,'Beverages',71,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(122,'Cooking & Recipes',71,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1512,'Food',71,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1523,'Food & Grocery Delivery',71,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(121,'Food & Grocery Retailers',71,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(276,'Restaurants',71,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(919,'Arcade & Coin-Op Games',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(920,'Board Games',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(39,'Card Games',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(41,'Computer & Video Games',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1492,'Dice Games',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1493,'Educational Games',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1290,'Family-Oriented Games & Activities',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(637,'Gambling',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(105,'Online Games',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(936,'Party Games',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(937,'Puzzles & Brainteasers',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(622,'Roleplaying Games',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(938,'Table Games',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1549,'Tile Games',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1494,'Word Games',8,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(623,'Aging & Geriatrics',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(499,'Alternative & Natural Medicine',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(419,'Health Conditions',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(254,'Health Education & Medical Training',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(252,'Health Foundations & Medical Research',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(251,'Medical Devices & Equipment',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(256,'Medical Facilities & Services',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(253,'Medical Literature & Resources',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(636,'Men''s Health',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(437,'Mental Health',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(418,'Nursing',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(456,'Nutrition',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(245,'Oral & Dental Care',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(645,'Pediatrics',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(248,'Pharmacy',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(947,'Public Health',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(195,'Reproductive Health',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(257,'Substance Abuse',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(246,'Vision Care',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(648,'Women''s Health',45,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(189,'Clubs & Organizations',65,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1276,'Contests, Awards & Prizes',65,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(284,'Crafts',65,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(688,'Outdoors',65,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(786,'Paintball',65,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(787,'Radio Control & Modeling',65,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(999,'Recreational Aviation',65,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(977,'Special Occasions',65,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1002,'Water Activities',65,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(948,'Bed & Bath',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(472,'Domestic Services',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(269,'Gardening & Landscaping',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(828,'HVAC & Climate Control',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(271,'Home Appliances',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(270,'Home Furnishings',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(158,'Home Improvement',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1348,'Home Storage & Shelving',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(137,'Homemaking & Interior Decor',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(951,'Kitchen & Dining',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1364,'Laundry',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1372,'Nursery & Playroom',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(471,'Pest Control',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(952,'Swimming Pools & Spas',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(953,'Yard & Patio',11,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(385,'Communications Equipment',13,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(394,'Email & Messaging',13,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(382,'Mobile & Wireless',13,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(485,'Search Engines',13,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(383,'Service Providers',13,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(392,'Teleconferencing',13,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1142,'Web Apps & Online Tools',13,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(301,'Web Portals',13,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(302,'Web Services',13,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(74,'Education',958,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1471,'Internships',958,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(60,'Jobs',958,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(76,'Government',19,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(75,'Legal',19,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(366,'Military',19,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(166,'Public Safety',19,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(508,'Social Services',19,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(112,'Broadcast & Network News',16,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(784,'Business News',16,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(507,'Gossip & Tabloid News',16,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1253,'Health News',16,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1204,'Journalism & News Industry',16,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(572,'Local News',16,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(408,'Newspapers',16,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(396,'Politics',16,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1077,'Sports News',16,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(785,'Technology News',16,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(63,'Weather',16,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1209,'World News',16,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(504,'Blogging Resources & Services',299,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(55,'Dating & Personals',299,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1482,'Feed Aggregation & Social Bookmarking',299,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(321,'File Sharing & Hosting',299,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(191,'Forum & Chat Providers',299,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(43,'Online Goodies',299,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(582,'Online Journals & Personal Sites',299,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(275,'Photo & Video Sharing',299,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(529,'Social Networks',299,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(972,'Virtual Worlds',299,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(677,'Disabled & Special Needs',14,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(56,'Ethnic & Identity Groups',14,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1131,'Family & Relationships',14,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(594,'Men''s Interests',14,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(59,'Religion & Belief',14,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(298,'Seniors & Retirement',14,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(54,'Social Issues & Advocacy',14,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(509,'Social Sciences',14,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(502,'Subcultures & Niche Interests',14,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(325,'Women''s Interests',14,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(882,'Animal Products & Services',66,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(563,'Pets',66,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(119,'Wildlife',66,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(378,'Apartments & Residential Rentals',29,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1460,'Bank-Owned & Foreclosed Properties',29,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1178,'Commercial & Investment Real Estate',29,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(687,'Property Development',29,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(463,'Property Inspections & Appraisals',29,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(425,'Property Management',29,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(96,'Real Estate Agencies',29,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1080,'Real Estate Listings',29,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1081,'Timeshares & Vacation Properties',29,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(527,'Directories & Listings',533,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(980,'General Reference',533,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1084,'Geographic Reference',533,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(474,'Humanities',533,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(108,'Language Resources',533,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(375,'Libraries & Museums',533,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1233,'Technical Reference',533,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(435,'Astronomy',174,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(440,'Biological Sciences',174,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(505,'Chemistry',174,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1227,'Computer Science',174,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1168,'Earth Sciences',174,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(442,'Ecology & Environment',174,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(231,'Engineering & Technology',174,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(436,'Mathematics',174,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(444,'Physics',174,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(445,'Scientific Equipment',174,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(446,'Scientific Institutions',174,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(64,'Antiques & Collectibles',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(68,'Apparel',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(292,'Auctions',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(61,'Classifieds',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(69,'Consumer Resources',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1505,'Discount & Outlet Stores',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1143,'Entertainment Media',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(70,'Gifts & Special Event Items',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1507,'Green & Eco-Friendly Shopping',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(696,'Luxury Goods',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(73,'Mass Merchants & Department Stores',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(576,'Photo & Video Services',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(531,'Shopping Portals & Search Engines',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1210,'Swap Meets & Outdoor Markets',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(123,'Tobacco Products',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(432,'Toys',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1225,'Wholesalers & Liquidators',18,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1073,'College Sports',20,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(514,'Combat Sports',20,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(554,'Extreme Sports',20,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(998,'Fantasy Sports',20,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1000,'Individual Sports',20,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(180,'Motor Sports',20,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1599,'Sport Scores & Statistics',20,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(263,'Sporting Goods',20,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1082,'Sports Coaching & Training',20,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1001,'Team Sports',20,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(118,'Water Sports',20,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(265,'Winter Sports',20,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1198,'World Sports Competitions',20,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(203,'Air Travel',67,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(708,'Bus & Rail',67,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(205,'Car Rental & Taxi Services',67,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1339,'Carpooling & Vehicle Sharing',67,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(206,'Cruises & Charters',67,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(179,'Hotels & Accommodations',67,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1003,'Luggage & Travel Accessories',67,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1004,'Specialty Travel',67,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(208,'Tourist Destinations',67,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1010,'Travel Agencies & Services',67,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(1011,'Travel Guides & Travelogues',67,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(5001,'Africa',5000,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(5028,'Asia',5000,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(5104,'Europe',5000,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(5203,'Latin America',5000,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(5588,'Middle East',5000,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(5237,'North America',5000,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(5335,'Oceania',5000,1);
INSERT INTO ASSET_REPO.SUBDOMAIN (id,NAME,domainId,version) VALUES(5353,'Polar Regions',5000,1);
